db_dir: "my_test_db"
schema_file: "schema.json"
table_dir: "tables"
database_name: "my_test_db"
log_dir: "my_test_logs"
log_file: "change_log.json"
repl_node_file: "nodes.json"
node_url: "http://localhost"
node_port: 8080

# New replication configuration section
replication:
  max_offline_duration: 86400 # 24 hours in seconds
  max_replication_attempts: 10
  retry_interval: 1 # 1 minutes in seconds
  sync_interval: 60 # Sync every 60 minutes - configure a value if you want it to be scheduled.  0 means that it's not scheduled at all and must be called manually.
